export {default as Container} from './Container'
export {default as Header} from './Header/Header'
export {default as HomeContent} from './Home-page/Home-content'
export {default as HomeExample} from './Home-page/Home-Example/HomeExample'
export {default as AboutUs} from './AboutUs/AboutUs'
export {default as Services} from './Services/Services'
export {default as Rent} from './Services/Rent/Rent'
export {default as Buy} from './Services/Buy/Buy'
export {default as NewProjects} from './Services/NewProjects/NewProjects'
export {default as Villa} from './Services/Villa/Villa'
export {default as Apartments} from './Services/Apartments/Apartments'
export {default as PrudectCard} from './PrudectCard/PrudectCard'
export {default as MoreDetails} from '../components/MoreDetails/MoreDetails'
export {default as PrivacyPolicy} from './PrivacyPolicy/PrivacyPolicy'
export {default as Blogs} from './Blogs/Blogs'
export {default as BlogsCard} from './Blogs/BlogsCard/BlogsCard'
export {default as Contact} from './Contact/Contact'
export {default as Footer} from './Footer/Footer'


export {default as Button} from './button'